### ISSUE TITLE
Why is the book in Brazilian?

### ISSUE THREAD

**Issue by pjcaldeira** [DiscoverMeteor/DiscoverMeteor_Pt#47]
I can't get to understand this?
Why is the book in Brazilian?
Microsoft and Google are asking for corrections in Portuguese and here I only see Brazilian!
Give me a break, do you!

**Comment by ibrahimcesar** [comment]
@pjcaldeira I'm from Brazil. 

I think because Brazilian is a bigger community (3 meetups, startups using Meteor in production, hackathons) and have more volunteers interested in translated to our own language.

And also, because it's a bigger market.

Perhaps there are shortage of devs from Portugal willing to contribute. It's an open source model, there are no mystery why.

**Comment by Carlosxell** [comment]
@ibrahimcesar you are totally right. :+1:

**Comment by pjcaldeira** [comment]
@ibrahimcesar @Carlosxell Both of you are completely wrong 👎
Even in Brazil are more than 3 milion Portuguese natives. Your arguments are completely outstanding.

**Comment by pjcaldeira** [comment]
👎

**Comment by Carlosxell** [comment]
We have different viewpoints, you continue with your and we with our....

**Comment by guilhermedecampo** [comment]
hahaha Brazil is a bigger market for sure.

But if I were a citizen from Portugal wouldn't be mad at all.
It is all translated and ok for people who doesn't know english which is the point.
